import "./TeroristsData.css";
import teroristsData from "../../terorists/terorists";
function TerirstsData() {
  return (
    <table className="TeroristsDataArea">
      <tbody>
        <tr>
          <th>שם</th>
          <th>אירגון</th>
          <th>מספר תקיפות</th>
          <th>סטטוס</th>
          <th>סיכום</th>
        </tr>
        <tr>
          <th>{teroristsData[0].name}</th>
          <th>{teroristsData[0].organization}</th>
          <th>{teroristsData[0].attacksCount}</th>
          <th>{teroristsData[0].status}</th>
          <th>{teroristsData[0].relationToIsraelSummary}</th>
        </tr>
        <tr>
          <th>{teroristsData[1].name}</th>
          <th>{teroristsData[1].organization}</th>
          <th>{teroristsData[1].attacksCount}</th>
          <th>{teroristsData[1].status}</th>
          <th>{teroristsData[1].relationToIsraelSummary}</th>
        </tr>
        <tr>
          <th>{teroristsData[2].name}</th>
          <th>{teroristsData[2].organization}</th>
          <th>{teroristsData[2].attacksCount}</th>
          <th>{teroristsData[2].status}</th>
          <th>{teroristsData[2].relationToIsraelSummary}</th>
        </tr>
        <tr>
          <th>{teroristsData[3].name}</th>
          <th>{teroristsData[3].organization}</th>
          <th>{teroristsData[3].attacksCount}</th>
          <th>{teroristsData[3].status}</th>
          <th>{teroristsData[3].relationToIsraelSummary}</th>
        </tr>
        <tr>
          <th>{teroristsData[4].name}</th>
          <th>{teroristsData[4].organization}</th>
          <th>{teroristsData[4].attacksCount}</th>
          <th>{teroristsData[4].status}</th>
          <th>{teroristsData[4].relationToIsraelSummary}</th>
        </tr>
        <tr>
          <th>{teroristsData[5].name}</th>
          <th>{teroristsData[5].organization}</th>
          <th>{teroristsData[5].attacksCount}</th>
          <th>{teroristsData[5].status}</th>
          <th>{teroristsData[5].relationToIsraelSummary}</th>
        </tr>
        <tr>
          <th>{teroristsData[6].name}</th>
          <th>{teroristsData[6].organization}</th>
          <th>{teroristsData[6].attacksCount}</th>
          <th>{teroristsData[6].status}</th>
          <th>{teroristsData[6].relationToIsraelSummary}</th>
        </tr>
        <tr>
          <th>{teroristsData[7].name}</th>
          <th>{teroristsData[7].organization}</th>
          <th>{teroristsData[7].attacksCount}</th>
          <th>{teroristsData[7].status}</th>
          <th>{teroristsData[7].relationToIsraelSummary}</th>
        </tr>
        <tr>
          <th>{teroristsData[8].name}</th>
          <th>{teroristsData[8].organization}</th>
          <th>{teroristsData[8].attacksCount}</th>
          <th>{teroristsData[8].status}</th>
          <th>{teroristsData[8].relationToIsraelSummary}</th>
        </tr>
        <tr>
          <th>{teroristsData[9].name}</th>
          <th>{teroristsData[9].organization}</th>
          <th>{teroristsData[9].attacksCount}</th>
          <th>{teroristsData[9].status}</th>
          <th>{teroristsData[9].relationToIsraelSummary}</th>
        </tr>
        <tr>
          <th>{teroristsData[10].name}</th>
          <th>{teroristsData[10].organization}</th>
          <th>{teroristsData[10].attacksCount}</th>
          <th>{teroristsData[10].status}</th>
          <th>{teroristsData[10].relationToIsraelSummary}</th>
        </tr>
        <tr>
          <th>{teroristsData[11].name}</th>
          <th>{teroristsData[11].organization}</th>
          <th>{teroristsData[11].attacksCount}</th>
          <th>{teroristsData[11].status}</th>
          <th>{teroristsData[11].relationToIsraelSummary}</th>
        </tr>
        <tr>
          <th>{teroristsData[12].name}</th>
          <th>{teroristsData[12].organization}</th>
          <th>{teroristsData[12].attacksCount}</th>
          <th>{teroristsData[12].status}</th>
          <th>{teroristsData[12].relationToIsraelSummary}</th>
        </tr>
        <tr>
          <th>{teroristsData[13].name}</th>
          <th>{teroristsData[13].organization}</th>
          <th>{teroristsData[13].attacksCount}</th>
          <th>{teroristsData[13].status}</th>
          <th>{teroristsData[13].relationToIsraelSummary}</th>
        </tr>
        <tr>
          <th>{teroristsData[14].name}</th>
          <th>{teroristsData[14].organization}</th>
          <th>{teroristsData[14].attacksCount}</th>
          <th>{teroristsData[14].status}</th>
          <th>{teroristsData[14].relationToIsraelSummary}</th>
        </tr>
        <tr>
          <th>{teroristsData[15].name}</th>
          <th>{teroristsData[15].organization}</th>
          <th>{teroristsData[15].attacksCount}</th>
          <th>{teroristsData[15].status}</th>
          <th>{teroristsData[15].relationToIsraelSummary}</th>
        </tr>
        <tr>
          <th>{teroristsData[16].name}</th>
          <th>{teroristsData[16].organization}</th>
          <th>{teroristsData[16].attacksCount}</th>
          <th>{teroristsData[16].status}</th>
          <th>{teroristsData[16].relationToIsraelSummary}</th>
        </tr>
        <tr>
          <th>{teroristsData[17].name}</th>
          <th>{teroristsData[17].organization}</th>
          <th>{teroristsData[17].attacksCount}</th>
          <th>{teroristsData[17].status}</th>
          <th>{teroristsData[17].relationToIsraelSummary}</th>
        </tr>
        <tr>
          <th>{teroristsData[18].name}</th>
          <th>{teroristsData[18].organization}</th>
          <th>{teroristsData[18].attacksCount}</th>
          <th>{teroristsData[18].status}</th>
          <th>{teroristsData[18].relationToIsraelSummary}</th>
        </tr>
        <tr>
          <th>{teroristsData[19].name}</th>
          <th>{teroristsData[19].organization}</th>
          <th>{teroristsData[19].attacksCount}</th>
          <th>{teroristsData[19].status}</th>
          <th>{teroristsData[19].relationToIsraelSummary}</th>
        </tr>
        <tr>
          <th>{teroristsData[20].name}</th>
          <th>{teroristsData[20].organization}</th>
          <th>{teroristsData[20].attacksCount}</th>
          <th>{teroristsData[20].status}</th>
          <th>{teroristsData[20].relationToIsraelSummary}</th>
        </tr>
        <tr>
          <th>{teroristsData[21].name}</th>
          <th>{teroristsData[21].organization}</th>
          <th>{teroristsData[21].attacksCount}</th>
          <th>{teroristsData[21].status}</th>
          <th>{teroristsData[21].relationToIsraelSummary}</th>
        </tr>
        <tr>
          <th>{teroristsData[22].name}</th>
          <th>{teroristsData[22].organization}</th>
          <th>{teroristsData[22].attacksCount}</th>
          <th>{teroristsData[22].status}</th>
          <th>{teroristsData[22].relationToIsraelSummary}</th>
        </tr>
        <tr>
          <th>{teroristsData[23].name}</th>
          <th>{teroristsData[23].organization}</th>
          <th>{teroristsData[23].attacksCount}</th>
          <th>{teroristsData[23].status}</th>
          <th>{teroristsData[23].relationToIsraelSummary}</th>
        </tr>
        <tr>
          <th>{teroristsData[24].name}</th>
          <th>{teroristsData[24].organization}</th>
          <th>{teroristsData[24].attacksCount}</th>
          <th>{teroristsData[24].status}</th>
          <th>{teroristsData[24].relationToIsraelSummary}</th>
        </tr>
        <tr>
          <th>{teroristsData[25].name}</th>
          <th>{teroristsData[25].organization}</th>
          <th>{teroristsData[25].attacksCount}</th>
          <th>{teroristsData[25].status}</th>
          <th>{teroristsData[25].relationToIsraelSummary}</th>
        </tr>
        <tr>
          <th>{teroristsData[26].name}</th>
          <th>{teroristsData[26].organization}</th>
          <th>{teroristsData[26].attacksCount}</th>
          <th>{teroristsData[26].status}</th>
          <th>{teroristsData[26].relationToIsraelSummary}</th>
        </tr>
        <tr>
          <th>{teroristsData[27].name}</th>
          <th>{teroristsData[27].organization}</th>
          <th>{teroristsData[27].attacksCount}</th>
          <th>{teroristsData[27].status}</th>
          <th>{teroristsData[27].relationToIsraelSummary}</th>
        </tr>
        <tr>
          <th>{teroristsData[28].name}</th>
          <th>{teroristsData[28].organization}</th>
          <th>{teroristsData[28].attacksCount}</th>
          <th>{teroristsData[28].status}</th>
          <th>{teroristsData[28].relationToIsraelSummary}</th>
        </tr>
        <tr>
          <th>{teroristsData[29].name}</th>
          <th>{teroristsData[29].organization}</th>
          <th>{teroristsData[29].attacksCount}</th>
          <th>{teroristsData[29].status}</th>
          <th>{teroristsData[29].relationToIsraelSummary}</th>
        </tr>
        <tr>
          <th>{teroristsData[30].name}</th>
          <th>{teroristsData[30].organization}</th>
          <th>{teroristsData[30].attacksCount}</th>
          <th>{teroristsData[30].status}</th>
          <th>{teroristsData[30].relationToIsraelSummary}</th>
        </tr>
        <tr>
          <th>{teroristsData[31].name}</th>
          <th>{teroristsData[31].organization}</th>
          <th>{teroristsData[31].attacksCount}</th>
          <th>{teroristsData[31].status}</th>
          <th>{teroristsData[31].relationToIsraelSummary}</th>
        </tr>
        <tr>
          <th>{teroristsData[32].name}</th>
          <th>{teroristsData[32].organization}</th>
          <th>{teroristsData[32].attacksCount}</th>
          <th>{teroristsData[32].status}</th>
          <th>{teroristsData[32].relationToIsraelSummary}</th>
        </tr>
        <tr>
          <th>{teroristsData[33].name}</th>
          <th>{teroristsData[33].organization}</th>
          <th>{teroristsData[33].attacksCount}</th>
          <th>{teroristsData[33].status}</th>
          <th>{teroristsData[33].relationToIsraelSummary}</th>
        </tr>
        <tr>
          <th>{teroristsData[34].name}</th>
          <th>{teroristsData[34].organization}</th>
          <th>{teroristsData[34].attacksCount}</th>
          <th>{teroristsData[34].status}</th>
          <th>{teroristsData[34].relationToIsraelSummary}</th>
        </tr>
        <tr>
          <th>{teroristsData[35].name}</th>
          <th>{teroristsData[35].organization}</th>
          <th>{teroristsData[35].attacksCount}</th>
          <th>{teroristsData[35].status}</th>
          <th>{teroristsData[35].relationToIsraelSummary}</th>
        </tr>
        <tr>
          <th>{teroristsData[36].name}</th>
          <th>{teroristsData[36].organization}</th>
          <th>{teroristsData[36].attacksCount}</th>
          <th>{teroristsData[36].status}</th>
          <th>{teroristsData[36].relationToIsraelSummary}</th>
        </tr>
        <tr>
          <th>{teroristsData[37].name}</th>
          <th>{teroristsData[37].organization}</th>
          <th>{teroristsData[37].attacksCount}</th>
          <th>{teroristsData[37].status}</th>
          <th>{teroristsData[37].relationToIsraelSummary}</th>
        </tr>
        <tr>
          <th>{teroristsData[38].name}</th>
          <th>{teroristsData[38].organization}</th>
          <th>{teroristsData[38].attacksCount}</th>
          <th>{teroristsData[38].status}</th>
          <th>{teroristsData[38].relationToIsraelSummary}</th>
        </tr>
      </tbody>
    </table>
  );
}

export default TerirstsData;
